In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [2]:

datas = load_wine()

df_wine = pd.DataFrame(np.c_[datas['data'], datas['target']],
                       columns=np.append(datas['feature_names'], ['target']))

In [3]:
df_wine.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0     0.0  
1                          3.40   1050.0     0.0  
2                          3.17   1185.0     0.0  
3                          3.45   1480.0     0.0  
4                          2.93    735.0     0.0

In [4]:
df_wine.shape

(178, 14)

In [6]:
df_wine.describe()

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  \
count       178.000000  178.000000                    178.000000   178.000000   
mean          5.058090    0.957449                      2.611685   746.893258   
std           2.318286    0.228572                      0.709990   314.907474   
min           1.280000    0.480000                      1.270000   278.000000   
25%           3.220000    0.782500                      1.937500   500.500000   
50%           4.690000    0.965000                      2.780000   673.500000   
75%           6.200000    1.120000                      3.170000   985.000000   
max          13.000000    1.710000                      4.000000  1680.000000   

           target  
count  178.000000  
mean     0.938202  
std      0.775035  
min      0.000000  
25%      0.000000  
50%      1.000000  
75%      2.000000  
max      2.000000

In [8]:
df_wine.dtypes

alcohol                         float64
malic_acid                      float64
ash                             float64
alcalinity_of_ash               float64
magnesium                       float64
total_phenols                   float64
flavanoids                      float64
nonflavanoid_phenols            float64
proanthocyanins                 float64
color_intensity                 float64
hue                             float64
od280/od315_of_diluted_wines    float64
proline                         float64
target                          float64
dtype: object

In [9]:
for column in df_wine.columns:
  print(f'{column}: {df_wine[column].isnull().sum()}')

alcohol: 0
malic_acid: 0
ash: 0
alcalinity_of_ash: 0
magnesium: 0
total_phenols: 0
flavanoids: 0
nonflavanoid_phenols: 0
proanthocyanins: 0
color_intensity: 0
hue: 0
od280/od315_of_diluted_wines: 0
proline: 0
target: 0


In [10]:
df_wine['target'].value_counts()

target
1.0    71
0.0    59
2.0    48
Name: count, dtype: int64

In [11]:
X = df_wine.drop('target', axis=1)
y = df_wine['target']

X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size=0.3, random_state=42)

In [14]:
for i in range(1, 4):
  model = DecisionTreeClassifier(criterion='gini', max_depth=i)
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  print("="*100)
  print("Profundidade da Árvore:", i)
  print("Acurácia:", accuracy_score(y_test, y_pred))
  print("="*100)
  print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred))
  print("="*100)
  print("Relatório de Classificação:\n", classification_report(y_test,
  y_pred))
  print("="*100)

Profundidade da Árvore: 1
Acurácia: 0.6111111111111112
Matriz de Confusão:
 [[17  2  0]
 [ 5 16  0]
 [14  0  0]]
Relatório de Classificação:
               precision    recall  f1-score   support

         0.0       0.47      0.89      0.62        19
         1.0       0.89      0.76      0.82        21
         2.0       0.00      0.00      0.00        14

    accuracy                           0.61        54
   macro avg       0.45      0.55      0.48        54
weighted avg       0.51      0.61      0.54        54

Profundidade da Árvore: 2
Acurácia: 0.8518518518518519
Matriz de Confusão:
 [[17  2  0]
 [ 5 16  0]
 [ 1  0 13]]
Relatório de Classificação:
               precision    recall  f1-score   support

         0.0       0.74      0.89      0.81        19
         1.0       0.89      0.76      0.82        21
         2.0       1.00      0.93      0.96        14

    accuracy                           0.85        54
   macro avg       0.88      0.86      0.86        54
weighted 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [16]:
for i in range(1,4):
  rf = RandomForestClassifier(n_estimators = 3, max_depth=i, max_features= 20, criterion='gini')
  rf.fit(X_train, y_train)
  y_pred = rf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("="*100)
  print("Profundidade da Árvore:", i)
  print("Acurácia:", accuracy_score(y_test, y_pred))
  print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred))
  print("Relatório de Classificação:\n", classification_report(y_test,
  y_pred))
  print("="*100)

Profundidade da Árvore: 1
Acurácia: 0.8333333333333334
Matriz de Confusão:
 [[17  2  0]
 [ 5 16  0]
 [ 2  0 12]]
Relatório de Classificação:
               precision    recall  f1-score   support

         0.0       0.71      0.89      0.79        19
         1.0       0.89      0.76      0.82        21
         2.0       1.00      0.86      0.92        14

    accuracy                           0.83        54
   macro avg       0.87      0.84      0.84        54
weighted avg       0.85      0.83      0.84        54

Profundidade da Árvore: 2
Acurácia: 0.8888888888888888
Matriz de Confusão:
 [[19  0  0]
 [ 5 16  0]
 [ 1  0 13]]
Relatório de Classificação:
               precision    recall  f1-score   support

         0.0       0.76      1.00      0.86        19
         1.0       1.00      0.76      0.86        21
         2.0       1.00      0.93      0.96        14

    accuracy                           0.89        54
   macro avg       0.92      0.90      0.90        54
weighted 

In [21]:
for i in range(1,6):
  knn = KNeighborsClassifier(n_neighbors=i)
  knn.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("="*100)
  print("Número de vizinhos:", i)
  print("Acurácia:", accuracy_score(y_test, y_pred))
  print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred))
  print("Relatório de Classificação:\n", classification_report(y_test,
  y_pred))
  print("="*100)

Número de vizinhos: 1
Acurácia: 0.7962962962962963
Matriz de Confusão:
 [[17  0  2]
 [ 3 16  2]
 [ 1  3 10]]
Relatório de Classificação:
               precision    recall  f1-score   support

         0.0       0.81      0.89      0.85        19
         1.0       0.84      0.76      0.80        21
         2.0       0.71      0.71      0.71        14

    accuracy                           0.80        54
   macro avg       0.79      0.79      0.79        54
weighted avg       0.80      0.80      0.80        54

Número de vizinhos: 2
Acurácia: 0.7037037037037037
Matriz de Confusão:
 [[17  0  2]
 [ 4 16  1]
 [ 2  7  5]]
Relatório de Classificação:
               precision    recall  f1-score   support

         0.0       0.74      0.89      0.81        19
         1.0       0.70      0.76      0.73        21
         2.0       0.62      0.36      0.45        14

    accuracy                           0.70        54
   macro avg       0.69      0.67      0.66        54
weighted avg     